// Dữ liệu 119 sound nhạc nền chuẩn xác theo phân loại thủ công của người dùng
// Đồng bộ 1-1 giữa Tool Tin Tức và Web Công Việc Hằng Ngày
const SOUNDBOARD_DATA = [
  {
    "id": "969490",
    "title": "Badtrip",
    "category": "01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "catName": "Tin Tức Giật Gân Căng Thẳng",
    "color": "red",
    "duration": 28.0,
    "author": "RPT MCK",
    "relPath": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/Badtrip [969490].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/Badtrip [969490].mp3",
    "folder": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "link": "https://www.tiktok.com/@scienceworld61/video/7569944879048969490",
    "flag": "--nhac \"Badtrip\""
  },
  {
    "id": "119496",
    "title": "Blood Theme (From Dexter )",
    "category": "01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "catName": "Tin Tức Giật Gân Căng Thẳng",
    "color": "red",
    "duration": 13.0,
    "author": "Carlos Marquez",
    "relPath": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/Blood Theme (From Dexter ) [119496].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/Blood Theme (From Dexter ) [119496].mp3",
    "folder": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "link": "https://www.tiktok.com/@endra4789/video/7550839964641119496",
    "flag": "--nhac \"Blood Theme (From Dexter )\""
  },
  {
    "id": "171487",
    "title": "Dizzy prod me",
    "category": "01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "catName": "Tin Tức Giật Gân Căng Thẳng",
    "color": "red",
    "duration": 7.0,
    "author": "CrayzMadeIt",
    "relPath": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/Dizzy prod me [171487].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/Dizzy prod me [171487].mp3",
    "folder": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "link": "https://www.tiktok.com/@purple.scar1/video/7532665263125171487",
    "flag": "--nhac \"Dizzy prod me\""
  },
  {
    "id": "036872",
    "title": "Ghép Cái Nhạc Trông Nghiêm Túc Hẳn",
    "category": "01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "catName": "Tin Tức Giật Gân Căng Thẳng",
    "color": "red",
    "duration": 12.0,
    "author": "D",
    "relPath": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/Ghép Cái Nhạc Trông Nghiêm Túc Hẳn [036872].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/Ghép Cái Nhạc Trông Nghiêm Túc Hẳn [036872].mp3",
    "folder": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "link": "https://www.tiktok.com/@hii.chauu/video/7490812502868036872",
    "flag": "--nhac \"Ghép Cái Nhạc Trông Nghiêm Túc Hẳn\""
  },
  {
    "id": "898373",
    "title": "I Can Do Anything Finale The Boys Soundtrack Epic Vibes Unleash...",
    "category": "01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "catName": "Tin Tức Giật Gân Căng Thẳng",
    "color": "red",
    "duration": 19.0,
    "author": "Viral Music Hits",
    "relPath": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/I Can Do Anything Finale The Boys Soundtrack Epic Vibes Unleash... [898373].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/I Can Do Anything Finale The Boys Soundtrack Epic Vibes Unleash... [898373].mp3",
    "folder": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "link": "https://www.tiktok.com/@viralmusichitsofficial/video/7466809975847898373",
    "flag": "--nhac \"I Can Do Anything Finale The Boys Soundtrack Epic Vibes Unleash...\""
  },
  {
    "id": "075604",
    "title": "Lucifer s Waltz",
    "category": "01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "catName": "Tin Tức Giật Gân Căng Thẳng",
    "color": "red",
    "duration": 6.0,
    "author": "Secession Studios",
    "relPath": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/Lucifer s Waltz [075604].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/Lucifer s Waltz [075604].mp3",
    "folder": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "link": "https://www.tiktok.com/@0pyum/video/7520343942815075604",
    "flag": "--nhac \"Lucifer s Waltz\""
  },
  {
    "id": "198994",
    "title": "Elab VinUni confirm là nhạc này làm mọi thứ trông",
    "category": "01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "catName": "Tin Tức Giật Gân Căng Thẳng",
    "color": "red",
    "duration": 15.0,
    "author": "Thuthuyy99",
    "relPath": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/nhạc nền - Thuthuyy99 [198994].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/nhạc nền - Thuthuyy99 [198994].mp3",
    "folder": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "link": "https://www.tiktok.com/@elab.vinuni/video/7350876090711198994",
    "flag": "--nhac \"Elab VinUni confirm là nhạc này làm mọi thứ trông\""
  },
  {
    "id": "958176",
    "title": "tense music",
    "category": "01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "catName": "Tin Tức Giật Gân Căng Thẳng",
    "color": "red",
    "duration": 59.0,
    "author": "soundeffectsforyou",
    "relPath": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/original sound - soundeffectsforyou [958176].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/original sound - soundeffectsforyou [958176].mp3",
    "folder": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "link": "https://www.tiktok.com/@soundeffectsforyou/video/7301079535921958176",
    "flag": "--nhac \"tense music\""
  },
  {
    "id": "820564",
    "title": "Golden Dragons Philharmonic Orchestra - Thunderfor",
    "category": "01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "catName": "Tin Tức Giật Gân Căng Thẳng",
    "color": "red",
    "duration": 246.0,
    "author": "GoldenDragonsEpic",
    "relPath": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/som original - GoldenDragonsEpic [820564].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/som original - GoldenDragonsEpic [820564].mp3",
    "folder": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "link": "https://www.tiktok.com/@goldendragonsepic/video/7632721381351820564",
    "flag": "--nhac \"Golden Dragons Philharmonic Orchestra - Thunderfor\""
  },
  {
    "id": "564230",
    "title": "Epic Neoclassic Trailer Music",
    "category": "01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "catName": "Tin Tức Giật Gân Căng Thẳng",
    "color": "red",
    "duration": 66.0,
    "author": "Alex",
    "relPath": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/оригинальный звук [564230].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/оригинальный звук [564230].mp3",
    "folder": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "link": "https://www.tiktok.com/@silversunmusic/video/7097498292132564230",
    "flag": "--nhac \"Epic Neoclassic Trailer Music\""
  },
  {
    "id": "756673",
    "title": "Forest fire  No Copyright Music for Dramatic   Epi",
    "category": "01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "catName": "Tin Tức Giật Gân Căng Thẳng",
    "color": "red",
    "duration": 183.0,
    "author": "chostomic",
    "relPath": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/오리지널 사운드 - chostomic [756673].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang/오리지널 사운드 - chostomic [756673].mp3",
    "folder": "nhac-nen/01_Tin_Tuc_Giat_Gan_Cang_Thang",
    "link": "https://www.tiktok.com/@chostomic/video/7490018387997756673",
    "flag": "--nhac \"Forest fire  No Copyright Music for Dramatic   Epi\""
  },
  {
    "id": "486919",
    "title": "Star Sky",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 60.0,
    "author": "Two Steps From Hell, Thomas Bergersen",
    "relPath": "nhac-nen/02_Vinh_Danh/Star Sky [486919].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/Star Sky [486919].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@05th_ng28/video/7516035574172486919",
    "flag": "--nhac \"Star Sky\""
  },
  {
    "id": "838356",
    "title": "Thịnh Vượng Việt Nam Sáng Ngời",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 33.0,
    "author": "Trường Linh Bùi",
    "relPath": "nhac-nen/02_Vinh_Danh/Thịnh Vượng Việt Nam Sáng Ngời [838356].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/Thịnh Vượng Việt Nam Sáng Ngời [838356].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@_be.xiu.scrp/video/7680224275713838356",
    "flag": "--nhac \"Thịnh Vượng Việt Nam Sáng Ngời\""
  },
  {
    "id": "226450",
    "title": "Có một Việt Nam như thế",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 24.0,
    "author": "CAPCUT 🍀",
    "relPath": "nhac-nen/02_Vinh_Danh/nhạc nền - CAPCUT [226450].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/nhạc nền - CAPCUT [226450].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@capcut_oanhhy247/video/7530206745810226450",
    "flag": "--nhac \"Có một Việt Nam như thế\""
  },
  {
    "id": "587330",
    "title": "Đám Cưới Như Mơ _Quang Linh",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 80.0,
    "author": "NguyễnDuy Official",
    "relPath": "nhac-nen/02_Vinh_Danh/nhạc nền - NguyễnDuy Official [587330].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/nhạc nền - NguyễnDuy Official [587330].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@user08211712/video/7313388644419587330",
    "flag": "--nhac \"Đám Cưới Như Mơ _Quang Linh\""
  },
  {
    "id": "521863",
    "title": "Chúc mừng Faker vô địch  LEGEND NEVER DIE X WARRIO",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 60.0,
    "author": "TINB MUSIC ⚜️",
    "relPath": "nhac-nen/02_Vinh_Danh/nhạc nền - TINB MUSIC [521863].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/nhạc nền - TINB MUSIC [521863].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@tinb.musix8/video/7303513822730521863",
    "flag": "--nhac \"Chúc mừng Faker vô địch  LEGEND NEVER DIE X WARRIO\""
  },
  {
    "id": "663426",
    "title": "Làng Trong Phố  bắt đầu từ đây",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 43.0,
    "author": "Trần Vân",
    "relPath": "nhac-nen/02_Vinh_Danh/nhạc nền - Trần Vân [663426].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/nhạc nền - Trần Vân [663426].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@vansat97/video/7263305123206663426",
    "flag": "--nhac \"Làng Trong Phố  bắt đầu từ đây\""
  },
  {
    "id": "182344",
    "title": "bóng đất nước hình như bóng dáng bao người...",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 52.0,
    "author": "VTV SHOWS",
    "relPath": "nhac-nen/02_Vinh_Danh/nhạc nền - VTV SHOWS [182344].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/nhạc nền - VTV SHOWS [182344].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@lgv_langkinhlg1/video/7447017524283182344",
    "flag": "--nhac \"bóng đất nước hình như bóng dáng bao người...\""
  },
  {
    "id": "174088",
    "title": "Thương người dân, thương người con, thương Việt Na",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 60.0,
    "author": "🎶 𝑩𝒂̉𝒏 𝑵𝒉𝒂̣𝒄 𝑺𝒖𝒚 🎶",
    "relPath": "nhac-nen/02_Vinh_Danh/nhạc nền - 𝑩𝒂 𝒏 𝑵𝒉𝒂 𝒄 𝑺𝒖𝒚 [174088].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/nhạc nền - 𝑩𝒂 𝒏 𝑵𝒉𝒂 𝒄 𝑺𝒖𝒚 [174088].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@ban_nhac_suy/video/7499073481972174088",
    "flag": "--nhac \"Thương người dân, thương người con, thương Việt Na\""
  },
  {
    "id": "110548",
    "title": "Majestic background music sound. Triumphant majest",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 157.0,
    "author": "Alec Koff Label MUSIC",
    "relPath": "nhac-nen/02_Vinh_Danh/original sound - Alec Koff Label MUSIC [110548].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/original sound - Alec Koff Label MUSIC [110548].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@alec_koff_music/video/7635856661261110548",
    "flag": "--nhac \"Majestic background music sound. Triumphant majest\""
  },
  {
    "id": "624263",
    "title": "Award background music for award ceremony, success",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 144.0,
    "author": "Alec Koff Label MUSIC",
    "relPath": "nhac-nen/02_Vinh_Danh/original sound - Alec Koff Label MUSIC [624263].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/original sound - Alec Koff Label MUSIC [624263].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@alec_koff_music/video/7566901668554624263",
    "flag": "--nhac \"Award background music for award ceremony, success\""
  },
  {
    "id": "795860",
    "title": "Inspirational background music sound. Inspiring ba",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 121.0,
    "author": "Alec Koff Label MUSIC",
    "relPath": "nhac-nen/02_Vinh_Danh/original sound - Alec Koff Label MUSIC [795860].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/original sound - Alec Koff Label MUSIC [795860].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@alec_koff_music/video/7623273291737795860",
    "flag": "--nhac \"Inspirational background music sound. Inspiring ba\""
  },
  {
    "id": "074887",
    "title": "Ca khúc dành cho kẻ chiến thắng",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 60.0,
    "author": "Mas Wawan",
    "relPath": "nhac-nen/02_Vinh_Danh/suara asli - Mas Wawan [074887].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/suara asli - Mas Wawan [074887].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@thng.minh7913/video/7639718674194074887",
    "flag": "--nhac \"Ca khúc dành cho kẻ chiến thắng\""
  },
  {
    "id": "209044",
    "title": "thêm tên nhạc dô phần cmt cùng nhau sài đi các tân",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 39.0,
    "author": "Cảm Ơn Người Đã Thức Cùng Tôi",
    "relPath": "nhac-nen/02_Vinh_Danh/âm thanh gốc - Cảm Ơn Người Đã Thức Cùng Tôi [209044].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/âm thanh gốc - Cảm Ơn Người Đã Thức Cùng Tôi [209044].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@thubancup/video/7674991561314209044",
    "flag": "--nhac \"thêm tên nhạc dô phần cmt cùng nhau sài đi các tân\""
  },
  {
    "id": "656199",
    "title": "À ơi, hoa bay lên trời, cây chi ở lại    Quê nhà x",
    "category": "02_Vinh_Danh",
    "catName": "Vinh Danh & Hào Hùng",
    "color": "yellow",
    "duration": 40.0,
    "author": "anlt",
    "relPath": "nhac-nen/02_Vinh_Danh/âm thanh gốc - anlt [656199].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/02_Vinh_Danh/âm thanh gốc - anlt [656199].mp3",
    "folder": "nhac-nen/02_Vinh_Danh",
    "link": "https://www.tiktok.com/@anlt.94/video/7662020323247656199",
    "flag": "--nhac \"À ơi, hoa bay lên trời, cây chi ở lại    Quê nhà x\""
  },
  {
    "id": "449409",
    "title": "BONI - Nhạc Học Tập & Chiêm Nghiệm",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 26.6,
    "author": "Boni của 20t🔥",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/BONI - Nhạc Học Tập & Chiêm Nghiệm [449409].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/BONI - Nhạc Học Tập & Chiêm Nghiệm [449409].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@gochoctap3/video/7690150730262449409",
    "flag": "--nhac \"BONI - Nhạc Học Tập & Chiêm Nghiệm\""
  },
  {
    "id": "879570",
    "title": "Great Little Things (Trap Version) - Hauxenz",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 116.8,
    "author": "𝕬𝖙𝖍𝖆𝖓 𝖁𝖚𝖊",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/Great Little Things (Trap Version) - Hauxenz [879570].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/Great Little Things (Trap Version) - Hauxenz [879570].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@athan.vue/video/7677889765533879570",
    "flag": "--nhac \"Great Little Things (Trap Version) - Hauxenz\""
  },
  {
    "id": "623378",
    "title": "HaruHaru No Guide melody Original by BIGBANG",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 47.0,
    "author": "歌っちゃ王",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/HaruHaru No Guide melody Original by BIGBANG [623378].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/HaruHaru No Guide melody Original by BIGBANG [623378].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@mocniemhy1808/video/7519120607720623378",
    "flag": "--nhac \"HaruHaru No Guide melody Original by BIGBANG\""
  },
  {
    "id": "536578",
    "title": "Nhắm Mắt Thấy Mùa Hè",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 59.0,
    "author": "𝙖𝙣𝙝𝙨𝙩𝙮𝙡𝙚😎",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/Nhắm Mắt Thấy Mùa Hè [536578].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/Nhắm Mắt Thấy Mùa Hè [536578].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@1010lykaka/video/7347252300500536578",
    "flag": "--nhac \"Nhắm Mắt Thấy Mùa Hè\""
  },
  {
    "id": "281044",
    "title": "Quyn Music - Tình Yêu Nhẹ Nhàng",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 60.1,
    "author": "Quyn Music",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/Quyn Music - Tình Yêu Nhẹ Nhàng [281044].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/Quyn Music - Tình Yêu Nhẹ Nhàng [281044].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@luxure313/video/7693447603941281044",
    "flag": "--nhac \"Quyn Music - Tình Yêu Nhẹ Nhàng\""
  },
  {
    "id": "918215",
    "title": "Thức Giấc",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 31.0,
    "author": "Da LAB",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/Thức Giấc [918215].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/Thức Giấc [918215].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@xphap_/video/7500164715297918215",
    "flag": "--nhac \"Thức Giấc\""
  },
  {
    "id": "trihngnngaco",
    "title": "Trời Hửng Nắng",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 187.0,
    "author": "Acoustic / Lofi",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/Trời Hửng Nắng - Acoustic Lofi Chill.mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/Trời Hửng Nắng - Acoustic Lofi Chill.mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "",
    "flag": "--nhac \"Trời Hửng Nắng\""
  },
  {
    "id": "289030",
    "title": "Trở Về",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 56.0,
    "author": "Wxrdie",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/Trở Về [289030].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/Trở Về [289030].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@metubmusic/video/7457902116112289030",
    "flag": "--nhac \"Trở Về\""
  },
  {
    "id": "246151",
    "title": "Đi để trở về",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 42.0,
    "author": "Títtt",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Cheese [246151].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Cheese [246151].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@tramwbear_63/video/7578503706430246151",
    "flag": "--nhac \"Đi để trở về\""
  },
  {
    "id": "272146",
    "title": "Người ta hay nói Việt Nam là một trong những quốc",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 29.0,
    "author": "Color of Memory",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Color of Memory [272146].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Color of Memory [272146].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@maucuakyuc/video/7600783283416272146",
    "flag": "--nhac \"Người ta hay nói Việt Nam là một trong những quốc\""
  },
  {
    "id": "664647",
    "title": "Và ngoài đó, hoang tàn giằng xé thì ở đây vẫn có đ",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 24.0,
    "author": "Feeling Soundzz",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Feeling Soundz [664647].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Feeling Soundz [664647].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@onlypassionmusic/video/7575006900555664647",
    "flag": "--nhac \"Và ngoài đó, hoang tàn giằng xé thì ở đây vẫn có đ\""
  },
  {
    "id": "021970",
    "title": "Có những vết đau rồi cũng đã lành..",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 47.0,
    "author": "Gen Z nghe gì ?",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Gen Z nghe gì [021970].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Gen Z nghe gì [021970].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@onlypassionmusic/video/7390197247541021970",
    "flag": "--nhac \"Có những vết đau rồi cũng đã lành..\""
  },
  {
    "id": "375623",
    "title": "Thắng - CHO TÔI LANG THANG ft. Đen Vâu",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 31.0,
    "author": "Hip Hop National VN",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Hip Hop National VN [375623].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Hip Hop National VN [375623].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@hiphopnationalvn/video/7483866288335375623",
    "flag": "--nhac \"Thắng - CHO TÔI LANG THANG ft. Đen Vâu\""
  },
  {
    "id": "320897",
    "title": "trước khi tuổi trẻ này đóng lối - NGẮN",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 49.0,
    "author": "NGẮN",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - NGẮN [320897].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - NGẮN [320897].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@nganofficical/video/7244873079854320897",
    "flag": "--nhac \"trước khi tuổi trẻ này đóng lối - NGẮN\""
  },
  {
    "id": "138010",
    "title": "Rồi có một ngày ta gặp nhau",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 59.0,
    "author": "Nat Original",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Nat Original [138010].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Nat Original [138010].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@nangmusiccorner/video/7204759598216138010",
    "flag": "--nhac \"Rồi có một ngày ta gặp nhau\""
  },
  {
    "id": "598549",
    "title": "Và hồn tôi từ đó Là khúc ca vang trong ngần Làm đô",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 22.0,
    "author": "Run Your Chill",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Run Your Chill [598549].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Run Your Chill [598549].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@th.vinh.trn6/video/7631777779788598549",
    "flag": "--nhac \"Và hồn tôi từ đó Là khúc ca vang trong ngần Làm đô\""
  },
  {
    "id": "741383",
    "title": "Đoạn intro của bài hát này có giai điệu hay nhất V",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 39.0,
    "author": "hadong",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - iamhadong [741383].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - iamhadong [741383].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@iamhadong/video/7538773020756741383",
    "flag": "--nhac \"Đoạn intro của bài hát này có giai điệu hay nhất V\""
  },
  {
    "id": "913877",
    "title": "Đen xin mời mọi người xem MV bài hát mới  Vị Nhà .",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 37.0,
    "author": "Đen Vâu official",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Đen Vâu official [913877].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/nhạc nền - Đen Vâu official [913877].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@den.vauvn/video/7460110149189913877",
    "flag": "--nhac \"Đen xin mời mọi người xem MV bài hát mới  Vị Nhà .\""
  },
  {
    "id": "626962",
    "title": "Đường về nhà có thể quanh co, chật hẹp, nhưng vẫn",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 36.0,
    "author": "Color of Memory",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/âm thanh gốc - Color of Memory [626962].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/âm thanh gốc - Color of Memory [626962].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@maucuakyuc/video/7678728195184626962",
    "flag": "--nhac \"Đường về nhà có thể quanh co, chật hẹp, nhưng vẫn\""
  },
  {
    "id": "982933",
    "title": "Cho Tôi Lang Thang - Đen ft.Ngọt",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 21.0,
    "author": "☝️🤓",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/âm thanh gốc - easy.ez [982933].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/âm thanh gốc - easy.ez [982933].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@eazyacong/video/7668910386694982933",
    "flag": "--nhac \"Cho Tôi Lang Thang - Đen ft.Ngọt\""
  },
  {
    "id": "263048",
    "title": "Đi để trở về 2",
    "category": "03_Nhac_Chiem_Nghiem",
    "catName": "Nhạc Chiêm Nghiệm & Đời Thường",
    "color": "brown",
    "duration": 42.0,
    "author": "hydrangea",
    "relPath": "nhac-nen/03_Nhac_Chiem_Nghiem/Đi để trở về 2 [263048].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/03_Nhac_Chiem_Nghiem/Đi để trở về 2 [263048].mp3",
    "folder": "nhac-nen/03_Nhac_Chiem_Nghiem",
    "link": "https://www.tiktok.com/@chill.withgenz/video/7454268331894263048",
    "flag": "--nhac \"Đi để trở về 2\""
  },
  {
    "id": "343570",
    "title": "Chúng Ta Của Tương Lai",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 83.0,
    "author": "Sơn Tùng M-TP",
    "relPath": "nhac-nen/04_Nhac_Buon/Chúng Ta Của Tương Lai [343570].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/Chúng Ta Của Tương Lai [343570].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@q.baosky96/video/7354958006108343570",
    "flag": "--nhac \"Chúng Ta Của Tương Lai\""
  },
  {
    "id": "614677",
    "title": "Sau Lời Từ Khước",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 45.0,
    "author": "Phan Mạnh Quỳnh",
    "relPath": "nhac-nen/04_Nhac_Buon/Sau Lời Từ Khước [614677].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/Sau Lời Từ Khước [614677].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@thhunh387/video/7650351290928614677",
    "flag": "--nhac \"Sau Lời Từ Khước\""
  },
  {
    "id": "425109",
    "title": "Tháng Tư Là Lời Nói Dối Của Em",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 27.0,
    "author": "Hà Anh Tuấn",
    "relPath": "nhac-nen/04_Nhac_Buon/Tháng Tư Là Lời Nói Dối Của Em [425109].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/Tháng Tư Là Lời Nói Dối Của Em [425109].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@fujii_01/video/7623594784946425109",
    "flag": "--nhac \"Tháng Tư Là Lời Nói Dối Của Em\""
  },
  {
    "id": "116754",
    "title": "Vì Anh Đâu Có Biết",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 33.0,
    "author": "Vũ.",
    "relPath": "nhac-nen/04_Nhac_Buon/Vì Anh Đâu Có Biết [116754].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/Vì Anh Đâu Có Biết [116754].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@xphap_/video/7425209928052116754",
    "flag": "--nhac \"Vì Anh Đâu Có Biết\""
  },
  {
    "id": "353415",
    "title": "Ngày cô ấy đi theo nơi phồn hoa",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 45.0,
    "author": "DzungMay",
    "relPath": "nhac-nen/04_Nhac_Buon/nhạc nền - DaLat duky [353415].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/nhạc nền - DaLat duky [353415].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@xphap_/video/7507626656786353415",
    "flag": "--nhac \"Ngày cô ấy đi theo nơi phồn hoa\""
  },
  {
    "id": "821704",
    "title": "Em Đừng Khóc   Chillies",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 56.0,
    "author": "Thị Thu Uyên Nguyễn",
    "relPath": "nhac-nen/04_Nhac_Buon/nhạc nền - Thị Thu Uyên Nguyễn [821704].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/nhạc nền - Thị Thu Uyên Nguyễn [821704].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@_nlat._/video/7671274298853821704",
    "flag": "--nhac \"Em Đừng Khóc   Chillies\""
  },
  {
    "id": "234388",
    "title": "nghe bài hát này bạn nhớ tới ai",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 33.0,
    "author": "🐼",
    "relPath": "nhac-nen/04_Nhac_Buon/nhạc nền - [234388].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/nhạc nền - [234388].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@.vtuyen29/video/7577397880374234388",
    "flag": "--nhac \"nghe bài hát này bạn nhớ tới ai\""
  },
  {
    "id": "504277",
    "title": "Có chàng trai viết lên cây..",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 26.0,
    "author": "𝑵𝒈𝒉𝒆 𝑮𝒊̀ 𝑯𝒐̂𝒎 𝑵𝒂𝒚",
    "relPath": "nhac-nen/04_Nhac_Buon/nhạc nền - 𝑵𝒈𝒉𝒆 𝑮𝒊 𝑯𝒐 𝒎 𝑵𝒂𝒚 [504277].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/nhạc nền - 𝑵𝒈𝒉𝒆 𝑮𝒊 𝑯𝒐 𝒎 𝑵𝒂𝒚 [504277].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@codonsomtoi_211/video/7645214186309504277",
    "flag": "--nhac \"Có chàng trai viết lên cây..\""
  },
  {
    "id": "750356",
    "title": "Xin Đừng Lặng Im - soobin",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 46.0,
    "author": "𝑈𝑦𝑛𝑛 💫⚡[𝐹𝐿𝑂𝑃]",
    "relPath": "nhac-nen/04_Nhac_Buon/nhạc nền - 𝓤𝔂𝓷𝓷 FLOP [750356].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/nhạc nền - 𝓤𝔂𝓷𝓷 FLOP [750356].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@ph3636366767/video/7685755788840750356",
    "flag": "--nhac \"Xin Đừng Lặng Im - soobin\""
  },
  {
    "id": "794578",
    "title": "nếu ngày ấy anh ngỏ lời thương..",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 31.0,
    "author": "𝙉𝙖𝙩𝙚 🌧",
    "relPath": "nhac-nen/04_Nhac_Buon/nhạc nền - 𝙉𝙖𝙩𝙚 [794578].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/nhạc nền - 𝙉𝙖𝙩𝙚 [794578].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@demxuongnhaclen/video/7662600727117794578",
    "flag": "--nhac \"nếu ngày ấy anh ngỏ lời thương..\""
  },
  {
    "id": "852308",
    "title": "Tháng năm -Soobin Hoàng Sơn-",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 51.0,
    "author": "Han Nhat Phong",
    "relPath": "nhac-nen/04_Nhac_Buon/nhạc nền - 𝙏𝐫𝐚𝐧 𝐃𝐮𝐜 [852308].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/nhạc nền - 𝙏𝐫𝐚𝐧 𝐃𝐮𝐜 [852308].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@maikti322/video/7663909917815852308",
    "flag": "--nhac \"Tháng năm -Soobin Hoàng Sơn-\""
  },
  {
    "id": "340566",
    "title": "still with you - jungkook",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 18.0,
    "author": "yuh",
    "relPath": "nhac-nen/04_Nhac_Buon/still with you - jungkook [340566].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/still with you - jungkook [340566].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@cpklyrics/video/7652997963987340566",
    "flag": "--nhac \"still with you - jungkook\""
  },
  {
    "id": "870356",
    "title": "thw mò",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 30.0,
    "author": "Bé Như",
    "relPath": "nhac-nen/04_Nhac_Buon/thw mò [870356].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/thw mò [870356].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@_wxrkey/video/7619573037997870356",
    "flag": "--nhac \"thw mò\""
  },
  {
    "id": "386196",
    "title": "Vậy là châm hết rồi đúng không...",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 26.0,
    "author": "Feeling Soundzz",
    "relPath": "nhac-nen/04_Nhac_Buon/âm thanh gốc - Feeling Soundz [386196].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/âm thanh gốc - Feeling Soundz [386196].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@onlypassionmusic/video/7675774068498386196",
    "flag": "--nhac \"Vậy là châm hết rồi đúng không...\""
  },
  {
    "id": "457365",
    "title": "Anh Đã Quen Với Cô Đơn - SOOBIN -",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 32.0,
    "author": "TOP",
    "relPath": "nhac-nen/04_Nhac_Buon/âm thanh gốc - TOP [457365].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/âm thanh gốc - TOP [457365].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@tuibidien385/video/7668235820922457365",
    "flag": "--nhac \"Anh Đã Quen Với Cô Đơn - SOOBIN -\""
  },
  {
    "id": "212744",
    "title": "mưa bổng ùa về trên căn gác vắng tí tách rơi từng",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 45.0,
    "author": "Văn Heo Xinh 🎭",
    "relPath": "nhac-nen/04_Nhac_Buon/âm thanh gốc - Văn Heo Xinh [212744].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/âm thanh gốc - Văn Heo Xinh [212744].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@pdvan06/video/7688664364408212744",
    "flag": "--nhac \"mưa bổng ùa về trên căn gác vắng tí tách rơi từng\""
  },
  {
    "id": "817362",
    "title": "đói view quáa",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 23.0,
    "author": "Prod.Zdot",
    "relPath": "nhac-nen/04_Nhac_Buon/âm thanh gốc - ZDOT23 [817362].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/âm thanh gốc - ZDOT23 [817362].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@prod.zdot/video/7625103789065817362",
    "flag": "--nhac \"đói view quáa\""
  },
  {
    "id": "706000",
    "title": "Sinh ra đã là thứ đối lập nhau - Emcee L(Da Lab)ft",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 30.0,
    "author": "just meow",
    "relPath": "nhac-nen/04_Nhac_Buon/âm thanh gốc - just meow [706000].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/âm thanh gốc - just meow [706000].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@roosterd/video/7679069257589706000",
    "flag": "--nhac \"Sinh ra đã là thứ đối lập nhau - Emcee L(Da Lab)ft\""
  },
  {
    "id": "773076",
    "title": "Cứ thế im lặng dần, cứ thế phai nhạt dần..",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 44.0,
    "author": "Đêm xuống nhạc lên",
    "relPath": "nhac-nen/04_Nhac_Buon/âm thanh gốc - Đêm xuống nhạc lên [773076].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/âm thanh gốc - Đêm xuống nhạc lên [773076].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@demxuongnhaclen/video/7689060220701773076",
    "flag": "--nhac \"Cứ thế im lặng dần, cứ thế phai nhạt dần..\""
  },
  {
    "id": "188822",
    "title": "Korean songs",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 28.0,
    "author": "khuseny🇺🇿",
    "relPath": "nhac-nen/04_Nhac_Buon/оригинальный звук [188822].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/оригинальный звук [188822].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@khuseny/video/7632958606526188822",
    "flag": "--nhac \"Korean songs\""
  },
  {
    "id": "659538",
    "title": "눈,코,입 (Eyes, Nose, Lips)",
    "category": "04_Nhac_Buon",
    "catName": "Nhạc Buồn & Lắng Đọng",
    "color": "blue",
    "duration": 60.0,
    "author": "TAEYANG",
    "relPath": "nhac-nen/04_Nhac_Buon/눈,코,입 (Eyes, Nose, Lips) [659538].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/04_Nhac_Buon/눈,코,입 (Eyes, Nose, Lips) [659538].mp3",
    "folder": "nhac-nen/04_Nhac_Buon",
    "link": "https://www.tiktok.com/@wannalisten2tunes/video/7512008246555659538",
    "flag": "--nhac \"눈,코,입 (Eyes, Nose, Lips)\""
  },
  {
    "id": "169365",
    "title": "Chinese Story Voice",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 15.0,
    "author": "Victor Cee",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/Chinese Story Voice [169365].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/Chinese Story Voice [169365].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@bucket_master1/video/7610728373358169365",
    "flag": "--nhac \"Chinese Story Voice\""
  },
  {
    "id": "550548",
    "title": "Cảm ơn anh độ Mixi nhưng QNT cảm ơn bằng nhạc Trung Quốc Women jin lờ.",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 28.0,
    "author": "Phục Chế Nhạc Căng Nhất 2026",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/Cảm ơn anh độ Mixi nhưng QNT cảm ơn bằng nhạc Trung Quốc Women jin lờ. [550548].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/Cảm ơn anh độ Mixi nhưng QNT cảm ơn bằng nhạc Trung Quốc Women jin lờ. [550548].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@phucchenhaccangnhat2026/video/7617637262154550548",
    "flag": "--nhac \"Cảm ơn anh độ Mixi nhưng QNT cảm ơn bằng nhạc Trung Quốc Women jin lờ.\""
  },
  {
    "id": "568645",
    "title": "Funny Viral Music for TikToks, Reels, and Shorts Nintendo Wii Mii T...",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 56.0,
    "author": "Viral Music Hits",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/Funny Viral Music for TikToks, Reels, and Shorts Nintendo Wii Mii T... [568645].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/Funny Viral Music for TikToks, Reels, and Shorts Nintendo Wii Mii T... [568645].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@viralmusichitsofficial/video/7492183035207568645",
    "flag": "--nhac \"Funny Viral Music for TikToks, Reels, and Shorts Nintendo Wii Mii T...\""
  },
  {
    "id": "428491",
    "title": "Funny Viral Music for TikToks, Reels, and Shorts Scheming Weasel ...",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 57.0,
    "author": "Viral Music Hits",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/Funny Viral Music for TikToks, Reels, and Shorts Scheming Weasel ... [428491].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/Funny Viral Music for TikToks, Reels, and Shorts Scheming Weasel ... [428491].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@viralmusichitsofficial/video/7580172181221428491",
    "flag": "--nhac \"Funny Viral Music for TikToks, Reels, and Shorts Scheming Weasel ...\""
  },
  {
    "id": "671431",
    "title": "Piano famous song Chopin Deep deep clear beauty",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 111.0,
    "author": "RYOpianoforte",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/Piano famous song Chopin Deep deep clear beauty [671431].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/Piano famous song Chopin Deep deep clear beauty [671431].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@cubination_player3/video/7564017428657671431",
    "flag": "--nhac \"Piano famous song Chopin Deep deep clear beauty\""
  },
  {
    "id": "209834",
    "title": "Sound Nhạc Meme",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 11.0,
    "author": "aryaseriouslol",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/Sound Nhạc Meme [209834].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/Sound Nhạc Meme [209834].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@aryaseriouslol/video/7450569026998209834",
    "flag": "--nhac \"Sound Nhạc Meme\""
  },
  {
    "id": "398102",
    "title": "new banger",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 28.0,
    "author": "𝘰𝘭𝘪𝘷𝘦𝘳.",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/new banger [398102].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/new banger [398102].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@mu_official09/video/7649337918376398102",
    "flag": "--nhac \"new banger\""
  },
  {
    "id": "731777",
    "title": "idea   bịp",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 30.0,
    "author": "traideparap",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/nhạc nền - Boo [731777].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/nhạc nền - Boo [731777].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@boofi1m/video/7343271310010731777",
    "flag": "--nhac \"idea   bịp\""
  },
  {
    "id": "148628",
    "title": "Lip Inc. - Funkytown Flute Fail - Meme Sound - Fun",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 110.0,
    "author": "Kayhin Music",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/nhạc nền - Kayhin Music [148628].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/nhạc nền - Kayhin Music [148628].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@kayhinmusic/video/7581419301266148628",
    "flag": "--nhac \"Lip Inc. - Funkytown Flute Fail - Meme Sound - Fun\""
  },
  {
    "id": "562002",
    "title": "chào em tui là anh chàng thư giãn...",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 20.0,
    "author": "NamNguyễn🍀",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/nhạc nền - music chill [562002].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/nhạc nền - music chill [562002].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@nguyn.tr.phng.nam/video/7441604050543562002",
    "flag": "--nhac \"chào em tui là anh chàng thư giãn...\""
  },
  {
    "id": "160072",
    "title": "1000 social credit",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 153.0,
    "author": "Ẩm Thực Trung Hoa",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/nhạc nền - Ẩm Thực Trung Hoa [160072].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/nhạc nền - Ẩm Thực Trung Hoa [160072].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@jaygameslol/video/7410358138295160072",
    "flag": "--nhac \"1000 social credit\""
  },
  {
    "id": "653342",
    "title": "Learn Chinese with viral song  生气了   Learn casual",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 47.0,
    "author": "Jay PinkHelmet Sings🎤",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/original sound - Jay [653342].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/original sound - Jay [653342].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@livaeasychinese/video/7670191044532653342",
    "flag": "--nhac \"Learn Chinese with viral song  生气了   Learn casual\""
  },
  {
    "id": "900997",
    "title": "Choi Yu Ree - Wish  . . . . . . . .",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 29.0,
    "author": "Edson_traduzpravoce",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/som original [900997].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/som original [900997].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@edson_traduzpravoce/video/7397513708550900997",
    "flag": "--nhac \"Choi Yu Ree - Wish  . . . . . . . .\""
  },
  {
    "id": "110098",
    "title": "French Meme Song - Meme Sound Effect  Thanks for w",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 14.0,
    "author": "abriliya",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/suara asli - Meme Effect Only [110098].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/suara asli - Meme Effect Only [110098].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@abrillyasan/video/7369431826844110098",
    "flag": "--nhac \"French Meme Song - Meme Sound Effect  Thanks for w\""
  },
  {
    "id": "576333",
    "title": "เส ยงต นฉบ บ - เพลงรวม Mix songs",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 37.0,
    "author": "NoNo 🐜🐜",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/เส ยงต นฉบ บ - เพลงรวม Mix songs [576333].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/เส ยงต นฉบ บ - เพลงรวม Mix songs [576333].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@shaggy_and_carl_dance/video/7637280218767576333",
    "flag": "--nhac \"เส ยงต นฉบ บ - เพลงรวม Mix songs\""
  },
  {
    "id": "308549",
    "title": "Nhất Tiễn Mai (一剪梅 - Xue Hua Piao Piao)",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 12.0,
    "author": "乔军",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/一剪梅 [308549].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/一剪梅 [308549].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@light.wisp/video/7370578785831308549",
    "flag": "--nhac \"Nhất Tiễn Mai (一剪梅 - Xue Hua Piao Piao)\""
  },
  {
    "id": "736706",
    "title": "Sound Nhạc Meme",
    "category": "05_Tin_Giai_Tri_Meme",
    "catName": "Tin Giải Trí (Meme)",
    "color": "yellow",
    "duration": 23.0,
    "author": "Fan",
    "relPath": "nhac-nen/05_Tin_Giai_Tri_Meme/오리지널 사운드 - hololive Fan [736706].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/05_Tin_Giai_Tri_Meme/오리지널 사운드 - hololive Fan [736706].mp3",
    "folder": "nhac-nen/05_Tin_Giai_Tri_Meme",
    "link": "https://www.tiktok.com/@mmdmad292/video/7041924867733736706",
    "flag": "--nhac \"Sound Nhạc Meme\""
  },
  {
    "id": "980423",
    "title": "2 Phút Hơn (KAIZ Remix)",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 20.0,
    "author": "Pháo",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/2 Phút Hơn (KAIZ Remix) [980423].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/2 Phút Hơn (KAIZ Remix) [980423].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@mikasa1glazer/video/7641439233973980423",
    "flag": "--nhac \"2 Phút Hơn (KAIZ Remix)\""
  },
  {
    "id": "484552",
    "title": "CHẠY NGAY ĐI",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 217.0,
    "author": "Sơn Tùng M-TP",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/CHẠY NGAY ĐI [484552].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/CHẠY NGAY ĐI [484552].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@3008tungmusic/video/7281878333145484552",
    "flag": "--nhac \"CHẠY NGAY ĐI\""
  },
  {
    "id": "630546",
    "title": "CÓ CHẮC YÊU LÀ ĐÂY",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 59.0,
    "author": "Sơn Tùng M-TP",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/CÓ CHẮC YÊU LÀ ĐÂY [630546].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/CÓ CHẮC YÊU LÀ ĐÂY [630546].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@luongnghia42/video/7536504426232630546",
    "flag": "--nhac \"CÓ CHẮC YÊU LÀ ĐÂY\""
  },
  {
    "id": "060871",
    "title": "Em Xinh",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 26.0,
    "author": "MONO, Onionn.",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Em Xinh [060871].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Em Xinh [060871].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@is.tuanhh_/video/7422707384277060871",
    "flag": "--nhac \"Em Xinh\""
  },
  {
    "id": "711510",
    "title": "Originalton",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 27.0,
    "author": "Maria",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Originalton [711510].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Originalton [711510].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@justtt.maria_/video/7463855915087711510",
    "flag": "--nhac \"Originalton\""
  },
  {
    "id": "623496",
    "title": "Pickleball",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 57.0,
    "author": "Đỗ Phú Quí",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Pickleball [623496].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Pickleball [623496].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@mmusic.records/video/7437469517686623496",
    "flag": "--nhac \"Pickleball\""
  },
  {
    "id": "743623",
    "title": "Sandwich Story",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 59.0,
    "author": "MONO, EmceeDan",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Sandwich Story [743623].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Sandwich Story [743623].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@mono.hng/video/7660754452105743623",
    "flag": "--nhac \"Sandwich Story\""
  },
  {
    "id": "563478",
    "title": "Some (feat. Lil Boi)",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 19.0,
    "author": "Soyou, Junggigo",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Some (feat. Lil Boi) [563478].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Some (feat. Lil Boi) [563478].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@user.nexaa/video/7541396674384563478",
    "flag": "--nhac \"Some (feat. Lil Boi)\""
  },
  {
    "id": "155336",
    "title": "The Playah (feat. SlimV) Special Performance",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 28.0,
    "author": "Soobin Hoàng Sơn",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/The Playah (feat. SlimV) Special Performance [155336].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/The Playah (feat. SlimV) Special Performance [155336].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@ngothtu_/video/7462735637553155336",
    "flag": "--nhac \"The Playah (feat. SlimV) Special Performance\""
  },
  {
    "id": "676370",
    "title": "Share Intro Bang Bang Bang PPTX",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 43.0,
    "author": "Ayko",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - Ayko [676370].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - Ayko [676370].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@hanazuzo/video/7486692513164676370",
    "flag": "--nhac \"Share Intro Bang Bang Bang PPTX\""
  },
  {
    "id": "024981",
    "title": "Soobin nhạc",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 32.0,
    "author": "Hyun 📸",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - Hyun [024981].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - Hyun [024981].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@qnhiw_/video/7668363491518024981",
    "flag": "--nhac \"Soobin nhạc\""
  },
  {
    "id": "469111",
    "title": "DANCING IN THE DARK - SOOBIN",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 59.0,
    "author": "NGUYENHAO",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - NGUYENHAO [469111].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - NGUYENHAO [469111].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@haonguyenchi242/video/7487469543355469111",
    "flag": "--nhac \"DANCING IN THE DARK - SOOBIN\""
  },
  {
    "id": "868743",
    "title": "Hazy Moon - Hatsune Miku - Lyric   Vietsub",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 250.0,
    "author": "Nhã mahiro cute",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - Nhã mahiro cute [868743].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - Nhã mahiro cute [868743].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@mahirooyamacute/video/7578327573566868743",
    "flag": "--nhac \"Hazy Moon - Hatsune Miku - Lyric   Vietsub\""
  },
  {
    "id": "891669",
    "title": "Bài này vẫn hay vc",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 16.0,
    "author": "TWEN MUSIC",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - ＴＷＥＮ [891669].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - ＴＷＥＮ [891669].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@_ihatetiktokk/video/7620251654536891669",
    "flag": "--nhac \"Bài này vẫn hay vc\""
  },
  {
    "id": "074706",
    "title": "Hãy Trao Cho Anh",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 41.0,
    "author": "ilry",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - 𝘽𝙤𝙢𝙗 [074706].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/nhạc nền - 𝘽𝙤𝙢𝙗 [074706].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@tramwbear_63/video/7612364197565074706",
    "flag": "--nhac \"Hãy Trao Cho Anh\""
  },
  {
    "id": "241287",
    "title": "lieu nhan gian may ai thuong nang",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 12.0,
    "author": "vizhsocute_",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/original sound - vì a chim bé nên làm vk a nhé [241287].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/original sound - vì a chim bé nên làm vk a nhé [241287].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@vizhsocute_/video/7572082902570241287",
    "flag": "--nhac \"lieu nhan gian may ai thuong nang\""
  },
  {
    "id": "111941",
    "title": "The Red Sun is in the Sky  is a Chinese propaganda",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 33.0,
    "author": "Corps Aktry",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/suara asli - Corps Aktry [111941].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/suara asli - Corps Aktry [111941].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@corpsaktry/video/7478016349223111941",
    "flag": "--nhac \"The Red Sun is in the Sky  is a Chinese propaganda\""
  },
  {
    "id": "823380",
    "title": "Quen Quen",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 21.0,
    "author": "ZUZ",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/âm thanh gốc - DUZ ( Âm Nhạc ) [823380].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/âm thanh gốc - DUZ ( Âm Nhạc ) [823380].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@15092014haizzz/video/7686729297947823380",
    "flag": "--nhac \"Quen Quen\""
  },
  {
    "id": "432085",
    "title": "Cưới đi - 2t   changg",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 40.0,
    "author": "Lz",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/âm thanh gốc - Lz [432085].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/âm thanh gốc - Lz [432085].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@tr4it1mcunqbtda0/video/7679335471725432085",
    "flag": "--nhac \"Cưới đi - 2t   changg\""
  },
  {
    "id": "601364",
    "title": "Sao anh chưa về nhà - amee ft. Ricky star",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 23.0,
    "author": "Lz",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/âm thanh gốc - Lz [601364].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/âm thanh gốc - Lz [601364].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@tr4it1mcunqbtda0/video/7687516457600601364",
    "flag": "--nhac \"Sao anh chưa về nhà - amee ft. Ricky star\""
  },
  {
    "id": "850772",
    "title": "Nhạc Sơn Tùng   Muộn rồi",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 22.0,
    "author": "Sin",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/âm thanh gốc - Sin [850772].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/âm thanh gốc - Sin [850772].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@sin._0o234/video/7607498699215850772",
    "flag": "--nhac \"Nhạc Sơn Tùng   Muộn rồi\""
  },
  {
    "id": "969040",
    "title": "Đừng Làm Trái Tim Anh Đau",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 59.0,
    "author": "Sơn Tùng M-TP",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Đừng Làm Trái Tim Anh Đau [969040].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/Đừng Làm Trái Tim Anh Đau [969040].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@nhacnaychillphet/video/7378124836695969040",
    "flag": "--nhac \"Đừng Làm Trái Tim Anh Đau\""
  },
  {
    "id": "612038",
    "title": "Nhạc Hàn này cuốn lắm nha mn ơi   Haru Haru Remix",
    "category": "06_Tin_Giai_Tri_Trend_Showbiz",
    "catName": "Tin Giải Trí (Trend Showbiz)",
    "color": "purple",
    "duration": 18.0,
    "author": "떰프",
    "relPath": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/오리지널 사운드 - 떰프₄₅₆ [612038].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz/오리지널 사운드 - 떰프₄₅₆ [612038].mp3",
    "folder": "nhac-nen/06_Tin_Giai_Tri_Trend_Showbiz",
    "link": "https://www.tiktok.com/@beatcuon/video/7691860745809612038",
    "flag": "--nhac \"Nhạc Hàn này cuốn lắm nha mn ơi   Haru Haru Remix\""
  },
  {
    "id": "chnvithanhxu",
    "title": "Có Hẹn Với Thanh Xuân",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 268.0,
    "author": "MONSTAR",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/Có Hẹn Với Thanh Xuân - MONSTAR.mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/Có Hẹn Với Thanh Xuân - MONSTAR.mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.youtube.com/watch?v=vpRi8S6uXAg",
    "flag": "--nhac \"Có Hẹn Với Thanh Xuân\""
  },
  {
    "id": "820501",
    "title": "Somebody's Pleasure - Aziz Hedra",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 27.7,
    "author": "astrooo🪐",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/Somebody's Pleasure - Aziz Hedra [820501].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/Somebody's Pleasure - Aziz Hedra [820501].mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.tiktok.com/@hadzz_spedxs/video/7693068731936820501",
    "flag": "--nhac \"Somebody's Pleasure - Aziz Hedra\""
  },
  {
    "id": "308370",
    "title": "a Rose",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 59.0,
    "author": "Hà Anh Tuấn | Friends",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/nhạc nền - Hà Anh Tuấn Friends [308370].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/nhạc nền - Hà Anh Tuấn Friends [308370].mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.tiktok.com/@salt.mixer/video/7486799550930308370",
    "flag": "--nhac \"a Rose\""
  },
  {
    "id": "699349",
    "title": "Từ ngày em đến ánh nắng ấy đã xua tan màn đêm nơi",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 39.0,
    "author": "Tô Hoà 81",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/nhạc nền - Tô Hoà 81 [699349].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/nhạc nền - Tô Hoà 81 [699349].mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.tiktok.com/@tramnoinho_lyrics/video/7647194327453699349",
    "flag": "--nhac \"Từ ngày em đến ánh nắng ấy đã xua tan màn đêm nơi\""
  },
  {
    "id": "211028",
    "title": "Đã Lỡ Yêu Em Nhiều   JustTee",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 49.0,
    "author": "Nhà của Dzun",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/nhạc nền - x.hieu [211028].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/nhạc nền - x.hieu [211028].mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.tiktok.com/@22h.nghenhac/video/7633458726011211028",
    "flag": "--nhac \"Đã Lỡ Yêu Em Nhiều   JustTee\""
  },
  {
    "id": "728392",
    "title": "Đưa Nhau Đi Trốn - Đen Vâu   ...",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 44.0,
    "author": "Đà Lạt +",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/nhạc nền - Đà Lạt [728392].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/nhạc nền - Đà Lạt [728392].mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.tiktok.com/@capcut_huutuyen77/video/7337937627271728392",
    "flag": "--nhac \"Đưa Nhau Đi Trốn - Đen Vâu   ...\""
  },
  {
    "id": "896392",
    "title": "Đi cùng anh từ khi bình minh vừa lên..",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 26.0,
    "author": "28th7",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/nhạc nền - 𝟮𝟴𝘁𝗵𝟳 [896392].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/nhạc nền - 𝟮𝟴𝘁𝗵𝟳 [896392].mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.tiktok.com/@onlypassionmusic/video/7356917907214896392",
    "flag": "--nhac \"Đi cùng anh từ khi bình minh vừa lên..\""
  },
  {
    "id": "707093",
    "title": "Thằng điên outro",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 37.0,
    "author": "Múic Vi Vu",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/original sound - Music Vi Vu [707093].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/original sound - Music Vi Vu [707093].mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.tiktok.com/@quan.bac.tu.halen/video/7577998341292707093",
    "flag": "--nhac \"Thằng điên outro\""
  },
  {
    "id": "469960",
    "title": "Em giờ đã có bầu trời mới       ...",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 28.0,
    "author": "embenhatdzi",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/original sound - đang giảm cân đừng hỏi [469960].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/original sound - đang giảm cân đừng hỏi [469960].mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.tiktok.com/@delwynaa/video/7422682890141469960",
    "flag": "--nhac \"Em giờ đã có bầu trời mới       ...\""
  },
  {
    "id": "477716",
    "title": "14 năm rồi  cây cầu  của JustaTee vẫn đỉnh   ...",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 30.0,
    "author": "Cái Page Nhạc Rap 🎶",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/âm thanh gốc - Cái Page Nhạc Rap [477716].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/âm thanh gốc - Cái Page Nhạc Rap [477716].mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.tiktok.com/@caipagenhacrap/video/7643396148140477716",
    "flag": "--nhac \"14 năm rồi  cây cầu  của JustaTee vẫn đỉnh   ...\""
  },
  {
    "id": "787796",
    "title": "Sinh ra đã là thứ đối lập nhau...",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 29.0,
    "author": "Feeling Soundzz",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/âm thanh gốc - Feeling Soundz [787796].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/âm thanh gốc - Feeling Soundz [787796].mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.tiktok.com/@onlypassionmusic/video/7677225284583787796",
    "flag": "--nhac \"Sinh ra đã là thứ đối lập nhau...\""
  },
  {
    "id": "552084",
    "title": "Cái bài hát gì mà nó yêu đời dữ",
    "category": "07_Nhac_Tinh_Yeu",
    "catName": "Nhạc Tình Yêu & Thanh Xuân",
    "color": "pink",
    "duration": 18.0,
    "author": "camenuong",
    "relPath": "nhac-nen/07_Nhac_Tinh_Yeu/âm thanh gốc - camenuong [552084].mp3",
    "absPath": "/Users/phuongpham/Downloads/Tool/Tool Tin Tức/nhac-nen/07_Nhac_Tinh_Yeu/âm thanh gốc - camenuong [552084].mp3",
    "folder": "nhac-nen/07_Nhac_Tinh_Yeu",
    "link": "https://www.tiktok.com/@anhdanau29/video/7671838636018552084",
    "flag": "--nhac \"Cái bài hát gì mà nó yêu đời dữ\""
  }
];

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { SOUNDBOARD_DATA };
}
